author: 若离QQ：2909998156
# 推送方式：0：邮件推送；1：qmsg推送；2：pushplus推送
send9999999
# 当且仅当sendType为0时有用，邮箱API的地址
emailApiUrl: 'https://api.ruoli.cc/mail/sendMail'
# 当且仅当sendType为1时有用，qmsg的Key（如需使用请自行更改）
myQmsgKey: ''
# submitForm提交数据进行加密的api接口
encryptApi: 'https://api.ruoli.cc/wise/getEncryption'


#用户组配置
##################################################
# 温馨提示：请仔细注意每个模板是属于哪个任务类型的配置！##
##################################################
users:
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20182693'
      #password 密码
      password: '68115tfq'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.398101
      #lat 纬度
      lat: 44.001899
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康

  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20182689'
      #password 密码
      password: 'qwer6666'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.398101
      #lat 纬度
      lat: 44.001899
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20182695'
      #password 密码
      password: 'zhz20000829'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.398101
      #lat 纬度
      lat: 44.001899
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
            
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20182674'
      #password 密码
      password: 'Llq13944291650'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.398101
      #lat 纬度
      lat: 44.001899
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
            
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20182669'
      #password 密码
      password: 'qnmbdhg3016'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.398101
      #lat 纬度
      lat: 44.001899
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
         
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20195576'
      #password 密码
      password: 'Aa15526660796.'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.398101
      #lat 纬度
      lat: 44.001899
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
            
  - user:
      # 任务类型（收集：0、签到：1、查寝：2）
      type: 1
      #username 学号或者工号
      username: '20182666'
      #password 密码
      password: 'hzp20182666'
      #address 地址，定位信息
      address: '中国吉林省长春市宽城区地理路'
      #sendKey 当sendType为0时代表邮箱，当sendType为1时代表接收消息的QQ号码，当sendType为2时代表接收消息的pushplus token
      sendKey: ''
      #school 学校全称
      schoolName: 长春工业大学
      # 附上经纬度查询地址（请自行选择自己的学校地址，address，lon，lat都要填查询到的）：http://api.map.baidu.com/lbsapi/getpoint/index.html
      #lon 经度
      lon: 125.398101
      #lat 纬度
      lat: 44.001899
      #abnormalReason 反馈信息（这个一般不用配置，但是不能删除，删除会报错）
      abnormalReason: ''
      #photo 签到照片，不需要可不填，或者直接删除
      photo: sign.jpg
      # 是否检查表单的标题（1代表检查，0代表不检查）
      checkTitle: 1
      #代理ip信息（格式为：网络协议://ip地址:端口   如：http://127.0.0.1:7890）
      proxy:
      # 表单信息
      forms:
        - form:
            title: 早测温
            value: 37.3度以下
        - form:
            title: 午测温
            value: 37.3度以下
        - form:
            title: 晚测温
            value: 37.3度以下
        - form:
            title: 健康状况
            value: 健康
